### PR TITLE
Fix Checkbox alignment with large texts

### LINKED ISSUE #1299: Checkbox label's unalignment
**Describe the bug**
On smaller widths, longer labels can get unaligned.

**To Reproduce**
On [Styleguide's page](https://styleguide.vtex.com/#/Components/Forms/Checkbox), replace the first example with the following code:
```initialState = { check1: true, check2: false }
;<div>
  <div className="mb3">
    <Checkbox
      checked={state.check1}
      id="option-0"
      label="Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit"
      name="default-checkbox-group"
      onChange={e => setState({ check1: !state.check1 })}
      value="option-0"
    />
  </div>
  <div className="mb3">
    <Checkbox
      checked={state.check2}
      partial={true}
      id="option-3"
      label="Curabitur ut quam vitae metus faucibus tincidunt."
      name="default-checkbox-group"
      onChange={e => setState({ check2: !state.check2 })}
      value="option-3"
    />
  </div>
</div>
```
and resize window.

**Expected behavior**
Labels should keep aligned.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by ericbreno**
#### What is the purpose of this pull request?
Fixes #1299 

#### What problem is this solving?
When the Checkbox has a text that breaks the line it overflows over the box, the problem is caused due to not having `min-width` property.

#### How should this be manually tested?
Have a checkbox with a text that cannot be displayed in a single line.

#### Screenshots or example usage
image

Before:
image

#### Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by ericbreno** [comment]
@jonathasbsouza updated with top-alignment for the checkbox. Please check screenshots of after/before if it is as expected.

File: react/components/Checkbox/index.js [hunk 1]
```diff
@@ -52,9 +53,12 @@ class Checkbox extends PureComponent {
           }
         )}>
         <div
-          className={classNames('vtex-checkbox__container relative w1 h1', {
-            mr3: label,
-          })}>
+          className={classNames(
+            `vtex-checkbox__container relative w1 h1 ${Styles.checkboxContainer}`,
```
Comment (estacioneto) [inline react/components/Checkbox/index.js:57]: Hou about this instead of adding this class?
1. Change `items-center` to `items-start` on container
2. Add `w-100` class to `label` element

**Comment by jonathasbsouza** [comment]
> @jonathasbsouza updated with top-alignment for the checkbox. Please check screenshots of after/before if it is as expected.

thanks!!

File: react/components/Checkbox/index.js (hunk 1 above)
Comment (ericbreno) [reply react/components/Checkbox/index.js:57]: Nice! Works like a charm

File: react/components/Checkbox/index.js [hunk 2]
```diff
@@ -46,13 +46,13 @@ class Checkbox extends PureComponent {
...
         className={classNames(
-          'vtex-checkbox__line-container flex items-center relative',
+          'vtex-checkbox__line-container flex items-start relative',
           {
             pointer: !disabled,
           }
         )}>
         <div
-          className={classNames('vtex-checkbox__container relative w1 h1', {
+          className={classNames(`vtex-checkbox__container relative w1 h1`, {
```
Comment (estacioneto) [inline react/components/Checkbox/index.js:55]: So you can rollback this then 😅 
```suggestion
          className={classNames('vtex-checkbox__container relative w1 h1', {
```

Comment (ericbreno) [reply react/components/Checkbox/index.js]: Done ✅
