### PR TITLE
Fix padding right to AutoComplete

### LINKED ISSUE #1306: AutoComplete padding-right is too big in Table V2
**Describe the bug**
When you have a long placehold (enough to touch the padding-right), you could see that padding-right is different than padding-left. This occurs because was sets this padding default to avoid overflow the CloseIcon.

**To Reproduce**
1. Go to AutoComplete in a TableV2 component.
2. Try to set a placeholder that overflow the input field.

**Expected behavior**
I think that is better to have a condition that changes this padding if CloseIcon is showing or not.

**Screenshots** 
Captura de tela de 2020-08-20 14-30-30

**Additional context**
If there's no problem, I can fix this issue :D

### PR DESCRIPTION
**Pull request by JuanBarros2**
#### What is the purpose of this pull request?
Fix #1306 

Creates a new condition to adjust the padding-right when CloseIconInput does not show. 

#### What problem is this solving?
[Running workspace](https://fixautocomplete--cosmetics1.myvtex.com/admin/app/collections/9259?tab=add)

#1306 

#### How should this be manually tested?
1- Try to put a long placehold in AutoCompleteInput 
2- Check if the padding is changing when the CloseIconInput isn't being shown.

#### Screenshots or example usage
Before
Captura de tela de 2020-08-24 11-24-53

After
Captura de tela de 2020-08-24 11-17-59

#### Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

File: react/components/AutocompleteInput/SearchInput/index.tsx [hunk 1]
```diff
@@ -93,12 +92,14 @@ const SearchInput: React.FC<PropTypes.InferProps<typeof propTypes> &
...
+  const showClearIcon = onClear && value
   const inputClasses = classNames(
     activeClass,
-    'w-100 ma0 border-box bw1 br2 ba outline-0 t-body ph5 pr8',
+    'w-100 ma0 border-box bw1 br2 ba outline-0 t-body ph5',
     {
       'br--left': onSearch,
-    }
+    },
+    `pr${showClearIcon ? 8 : 5}`
```
Comment (lucasecdb) [inline react/components/AutocompleteInput/SearchInput/index.tsx:102]: nit

```suggestion
      'pr5': !showClearIcon,
      'pr8': showClearIcon,
    },
```
